trigger:
  branches:
    include:
    - master
  paths:
    include:
      - 'apis/user-java'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        dockerfile: 'apis/user-java/Dockerfile'
        repository: 'devopsoh/api-user'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
